name: Scala CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Nix
        uses: jpaju/gh-commons/actions/setup-nix@main

      - name: Check formatting
        run: nix develop --command scala-cli scalafmt --check .

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Nix
        uses: jpaju/gh-commons/actions/setup-nix@main

      - name: Run unit tests
        run: nix develop --command scala-cli test .
